Change project name

diff --git a/aliases/alias/add b/aliases/alias/add
--- a/aliases/alias/add
+++ b/aliases/alias/add
@@ -1,23 +1,49 @@
 #!/bin/bash
 
-script_name="$1"
-script_path="$HOME/aliases/$script_name"
-alias_name="$script_name"
-
-shift
 command="$@"
+
+# Get name for the creating alias script
+read -p "Enter alias name: " alias_name
+if [ -z "$alias_name" ]; then
+    echo "Alias name is required"
+    exit 1
+fi
+
+# Get is in local or global alias and determine the script folder
+read -p "Local or global alias? (l/g): " alias_type
+script_dir=""
+if [ "$alias_type" == "l" ]; then
+    script_dir="$HOME/aliases/$LETDEV_PROFILE"
+elif [ "$alias_type" == "g" ]; then
+    script_dir="./.letdev/$LETDEV_PROFILE"
+else
+    echo "Invalid alias type"
+    exit 1
+fi 
 
 [ -n "$command" ] && echo "Add alias ':$alias_name' for the command '$command'"
 [ -z "$command" ] && echo "Add alias ':$alias_name'"
 
-mkdir -p "$HOME/aliases"
+mkdir -p "$script_dir"
+script_path="$script_dir/$alias_name.sh"
+
+[ -f "$script_path" ] && echo "Alias with the name '$alias_name' already exists" && exit 1
 
 touch "$script_path"
 chmod +x $script_path
-alias ":$alias_name"="source $script_path"
 
-echo "#! /bin/bash" > "$script_path"
+if [ "$alias_type" == "g" ]; then
+    alias ":$alias_name"="source $script_path"
+fi
+
+echo "#!/bin/bash" > "$script_path"
 echo "" >> "$script_path"
 [ -n "$command" ] && echo "$command" >> "$script_path"
 
-[ -z "$command" ] && mcedit "$script_path"
+# Open script in default editor, if any. Otherwise, use vim
+if [ -n "$EDITOR" ]; then
+    $EDITOR $script_path
+else
+    vim $script_path
+fi
+
