Formatting

diff --git a/commands/env/write b/commands/env/write
--- a/commands/env/write
+++ b/commands/env/write
@@ -6,43 +6,43 @@ COMMAND_DESCRIPTION="Write a new value to a variable in the .env file"
 COMMAND_HELP="\
 Write a new value to a variable in the .env file.
 Usage:
-  :env:write <env_file> <variable_name> <new_value>
+    :env:write <env_file> <variable_name> <new_value>
 Example:
-  :env:read .env MY_ENV_VAR 'new_value'
+    :env:read .env MY_ENV_VAR 'new_value'
 "
 
 _do_command() {
     if [[ "$1" = "--help" ]]; then
-      echo "$COMMAND_HELP"
-      return
+        echo "$COMMAND_HELP"
+        return
     fi
-    
-  if [[ "$#" -ne 3 ]]; then
-    # echo "Invalid number of arguments"
-    return 1
-  fi
 
-  local ENV_FILE="$1"
-  local VARIABLE_NAME="$2"
-  local NEW_VALUE="$3"
-
-  if [ ! -f "$ENV_FILE" ]; then
-    # echo "File $ENV_FILE does not exist"
-    return 1
-  fi
-
-  # Check if the variable exists in the .env file
-  if ! grep -q "^$VARIABLE_NAME=" $ENV_FILE; then
-    # If there are no new lines at the end of the file, add one
-    if [ "$(tail -c 1 $ENV_FILE)" != "" ]; then
-      echo "" >> $ENV_FILE
+    if [[ "$#" -ne 3 ]]; then
+        # echo "Invalid number of arguments"
+        return 1
     fi
-    # Append the variable to the end of the file
-    echo "$VARIABLE_NAME=$NEW_VALUE" >> $ENV_FILE
-  else
-    # Use sed to replace the variable value in the .env file
-    sed -i "" "s/^$VARIABLE_NAME=.*/$VARIABLE_NAME=$NEW_VALUE/" $ENV_FILE
-  fi
+
+    local ENV_FILE="$1"
+    local VARIABLE_NAME="$2"
+    local NEW_VALUE="$3"
+
+    if [ ! -f "$ENV_FILE" ]; then
+        # echo "File $ENV_FILE does not exist"
+        return 1
+    fi
+
+    # Check if the variable exists in the .env file
+    if ! grep -q "^$VARIABLE_NAME=" $ENV_FILE; then
+        # If there are no new lines at the end of the file, add one
+        if [ "$(tail -c 1 $ENV_FILE)" != "" ]; then
+            echo "" >>$ENV_FILE
+        fi
+        # Append the variable to the end of the file
+        echo "$VARIABLE_NAME=$NEW_VALUE" >>$ENV_FILE
+    else
+        # Use sed to replace the variable value in the .env file
+        sed -i "" "s/^$VARIABLE_NAME=.*/$VARIABLE_NAME=$NEW_VALUE/" $ENV_FILE
+    fi
 }
 
 _do_command "$@"
diff --git a/commands/git/set-git-user-for-project b/commands/git/set-git-user-for-project
--- a/commands/git/set-git-user-for-project
+++ b/commands/git/set-git-user-for-project
@@ -1,46 +1,56 @@
 #!/usr/bin/env bash
 #set -euo pipefail
 
-# Update git settings for the project with the GitHub account
+COMMAND_DESCRIPTION="Update project git GitHub account."
 
-# Help
-if [ "$1" == "--help" ]; then
-    echo "Usage: $0 <github_account> <email> [project_dir]"
-    exit 0
-fi
+COMMAND_HELP="\
+Update git settings for the project to use specified GitHub account.
+Usage: 
+    :git:set-git-user-for-project <github_account> <email> [project_dir]
+"
 
-# Variables
-github_account=$1
-email=$2
-project_dir=$3
+_do_command() {
+    if [[ "$1" = "--help" ]]; then
+        echo "$COMMAND_HELP"
+        return
+    fi
 
-# Check if the GitHub account is provided
-if [ -z "$github_account" ]; then
-    echo "GitHub account is required"
-    exit 1
-fi
+    # Variables
+    local github_account=$1
+    local email=$2
+    local project_dir=$3
 
-# Check if the email is provided
-if [ -z "$email" ]; then
-    echo "Email is required"
-    exit 1
-fi
+    # Check if the GitHub account is provided
+    if [ -z "$github_account" ]; then
+        echo "GitHub account is required"
+        exit 1
+    fi
 
-# Check if the project directory is provided or use the current directory
-[ -z "$project_dir" ] && project_dir="."
+    # Check if the email is provided
+    if [ -z "$email" ]; then
+        email=$(eval ": :git:github-no-reply-email '$github_account'")
+        echo "Email is not specified, use no-reply github address: $email"
+    fi
 
-# Check if the project directory exists
-if [ ! -d "$project_dir" ]; then
-    echo "Project directory does not exist: $project_dir"
-    exit 1
-fi
+    # Check if the project directory is provided or use the current directory
+    [ -z "$project_dir" ] && project_dir="."
 
-# Update the git settings for the project
-if [ "$project_dir" != "." ]; then
-    cd "$project_dir"
-fi
+    # Check if the project directory exists
+    if [ ! -d "$project_dir" ]; then
+        echo "Project directory does not exist: $project_dir"
+        exit 1
+    fi
 
-git config user.name "$github_account"
-git config user.email "$email"
+    # Update the git settings for the project
+    if [ "$project_dir" != "." ]; then
+        cd "$project_dir"
+    fi
 
-echo "Git settings updated for the project: $project_dir"
+    git config user.name "$github_account"
+    git config user.email "$email"
+
+    echo "Git settings updated for the project: $project_dir"
+}
+
+_do_command $@
+
diff --git a/commands/git/set-git-user-global b/commands/git/set-git-user-global
--- a/commands/git/set-git-user-global
+++ b/commands/git/set-git-user-global
@@ -1,32 +1,42 @@
 #!/usr/bin/env bash
 #set -euo pipefail
 
-# Update git settings for the project with the GitHub account
+COMMAND_DESCRIPTION="Update global git GitHub account."
 
-# Help
-if [ "$1" == "--help" ]; then
-    echo "Usage: $0 <github_account> <email> [project_dir]"
-    exit 0
-fi
+COMMAND_HELP="\
+Update global git settings to use specified GitHub account.
+Usage: 
+    :git:set-git-user-for-global <github_account> <email> [project_dir]
+"
 
-# Variables
-github_account=$1
-email=$2
-project_dir=$3
+_do_command() {
+    if [[ "$1" = "--help" ]]; then
+        echo "$COMMAND_HELP"
+        return
+    fi
 
-# Check if the GitHub account is provided
-if [ -z "$github_account" ]; then
-    echo "GitHub account is required"
-    exit 1
-fi
+    # Variables
+    local github_account=$1
+    local email=$2
+    local project_dir=$3
 
-# Check if the email is provided
-if [ -z "$email" ]; then
-    echo "Email is required"
-    exit 1
-fi
+    # Check if the GitHub account is provided
+    if [ -z "$github_account" ]; then
+        echo "GitHub account is required"
+        exit 1
+    fi
 
-git config --global user.name "$github_account"
-git config --global user.email "$email"
+    # Check if the email is provided
+    if [ -z "$email" ]; then
+        email=$(eval ": :git:github-no-reply-email '$github_account'")
+        echo "Email is not specified, use no-reply github address: $email"
+    fi
 
-echo "Git settings updated globally"
+    git config --global user.name "$github_account"
+    git config --global user.email "$email"
+
+    echo "Git settings updated globally"
+}
+
+_do_command $@
+ 
